### ISSUE TITLE
CRUD for subjects

### ISSUE THREAD

**Issue by janbujanowski** [SGGW-mgr-2018/KorepetycjeNaJuz-API#35]

**Comment by magdasid** [comment]
@dokrasa kiedy task będzie gotowy?

**Comment by dokrasa** [comment]
@magdasid możliwe, że jutro na kubicy zrobię. A na kiedy to ma być?

**Comment by magdasid** [comment]
Temat lekcji dodaje się do bazy, ale leci 500. @dokrasa proszę o poprawienie.
