### ISSUE TITLE
AddNewCoachLesson

### ISSUE THREAD

**Issue by janbujanowski** [SGGW-mgr-2018/KorepetycjeNaJuz-API#54]

**Comment by magdasid** [comment]
@KapibaraPiotr na kiedy task będzie gotowy?

**Comment by KapibaraPiotr** [comment]
Jest pewna szansa, że dzisiaj.

**Comment by Leivin** [comment]
Jak wygląda sytuacja?

**Comment by KapibaraPiotr** [comment]
Sytuacja jest taka, że dziś jest już zrobione.

**Comment by magdasid** [comment]
Nie może być możliwości dodawania CoachLesson komuś innemu, wystarczy że podamy nie swoje coachId i dodajemy lekcje komuś innemu. @KapibaraPiotr proszę o poprawienie.

**Comment by KapibaraPiotr** [comment]
Jutro zostanie poprawione.

**Comment by magdasid** [comment]
@KapibaraPiotr i jak tam poprawki?

**Comment by KapibaraPiotr** [comment]
Rozkminiam, jak to odpowiednio pushować i wstawiam
